apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ application }}-{{ version }}-{{ release }}"
spec:
  replicas: {{ replicas }}
  template:
    metadata:
      labels:
        application: "{{ application }}"
        version: "{{ version }}"
        release: "{{ release }}"
        stage: production
      ## OPTIONAL: AWS IAM role (must be created separately via CF) to use
      # annotations:
      #   iam.amazonaws.com/role: "app-{{ application }}"
    spec:
      containers:
        - name: "{{ application }}"
          image: "registry.opensource.zalan.do/teapot/nginx-hello-world:{{ version }}"
          env:
            # for JVM applications:
            # set the maximum available memory as JVM would assume host/node capacity otherwise
            # this is evaluated by java-dynamic-memory-opts in the Zalando OpenJDK base image
            # see https://github.com/zalando/docker-openjdk
            - name: MEM_TOTAL_KB
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Ki
            - name: SOME_ENV_VAR
              value: "Some example config value"
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              memory: 200Mi
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
